# Generated by Django 5.1.2 on 2024-10-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SMILES', models.CharField(blank=True, max_length=255, null=True)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Class', models.CharField(blank=True, max_length=255, null=True)),
                ('Formula', models.CharField(blank=True, max_length=255, null=True)),
                ('Molecular_mass', models.FloatField(blank=True, null=True, verbose_name='Molecular mass (g/mol)')),
                ('CN_literature', models.FloatField(blank=True, null=True)),
                ('dnAB', models.FloatField(blank=True, null=True)),
                ('dnCCDB', models.FloatField(blank=True, null=True)),
                ('dnQC', models.FloatField(blank=True, null=True)),
                ('g_CH3', models.FloatField(blank=True, null=True)),
                ('g_CH2_linear', models.FloatField(blank=True, null=True)),
                ('g_OH', models.FloatField(blank=True, null=True)),
                ('g_O_linear', models.FloatField(blank=True, null=True)),
                ('g_O_ring', models.FloatField(blank=True, null=True)),
                ('Ketone_linear', models.FloatField(blank=True, null=True)),
                ('Ketone_ring', models.FloatField(blank=True, null=True)),
                ('Aldehyde', models.FloatField(blank=True, null=True)),
                ('Ester_linear', models.FloatField(blank=True, null=True)),
                ('g_CH_linear', models.FloatField(blank=True, null=True)),
                ('g_CHdb_linear', models.FloatField(blank=True, null=True, verbose_name='g_CHdb_linear')),
                ('g_CHdb_ring', models.FloatField(blank=True, null=True)),
                ('g_CH2db_linear', models.FloatField(blank=True, null=True)),
                ('g_CH_ring', models.FloatField(blank=True, null=True)),
                ('g_CH2_ring', models.FloatField(blank=True, null=True)),
                ('Carboxylic_acid', models.FloatField(blank=True, null=True)),
                ('Mod_Leiden', models.FloatField(blank=True, null=True)),
                ('CN_predicted', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='molecules')),
            ],
        ),
    ]
